name: mldemos
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  flutter_staggered_grid_view: ^0.2.1

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Autobus
      fonts:
        - asset: assets/fonts/autobus/autobus-bold.ttf
    - family: PT Mono
      fonts:
        - asset: assets/fonts/pt-mono/pt-mono.ttf
        - asset: assets/fonts/pt-mono/pt-mono-bold.ttf
          weight: 700